### ISSUE TITLE
[Request] conda-forge compatible env.yaml

### ISSUE THREAD

**Issue by muhark** [KuleenS/VLMBiasEval#4]
Hello,

Thank you so much for this wonderful work and great codebase.

Would it be possible to provide an conda environment file that doesn't use the `default` channel from anaconda? This would allow researchers who cannot use the commercial version of Anaconda to utilize your code.

(I'm working on converting it right now, if convenient I can share the environment.yml once I've checked that everything works as intended).

Thank you!

-Musashi

**Comment by KuleenS** [comment]
Working on it right now! Thank you for your interest!

**Comment by KuleenS** [comment]
Updated with a new conda env. Try it out!

**Comment by muhark** [comment]
Amazing, it works :) Thank you for getting back so quickly!

For future users, note I needed to disable strict channel priority when installing, i.e.

```bash
mamba env create -f vlmbiaseval.yaml --no-channel-priority
```
